export type Secteur = string;

export interface Valeur {
  nom: string;
  ticker: string; // ticker Yahoo Finance
  mnemo: string; // code affiché (mnémonique Euronext ou ticker US)
  secteur: Secteur;
  siege: string; // pays du siège social
}

export type CodeUnivers = "sbf120" | "sp500";

// Univers SBF 120 : CAC 40 + 80 valeurs supplémentaires liquides
// d'Euronext Paris.
//
// ⚠️ Pour les 40 valeurs du CAC 40, les tickers ont été vérifiés
// individuellement. Pour les ~80 valeurs supplémentaires, la composition
// provient d'un relevé daté de décembre 2024 et les tickers sont une
// reconstitution de bonne foi, non vérifiée valeur par valeur — une valeur
// avec un ticker incorrect affichera simplement "—" plutôt que de casser
// la page.
export const SBF120: Valeur[] = [
  { nom: "Accor", ticker: "AC.PA", mnemo: "AC", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "ADP (Aéroports de Paris)", ticker: "ADP.PA", mnemo: "ADP", secteur: "Transport & Logistique", siege: "France" },
  { nom: "Air France-KLM", ticker: "AF.PA", mnemo: "AF", secteur: "Transport & Logistique", siege: "France" },
  { nom: "Air Liquide", ticker: "AI.PA", mnemo: "AI", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Airbus", ticker: "AIR.PA", mnemo: "AIR", secteur: "Aéronautique & Défense", siege: "Pays-Bas" },
  { nom: "Alstom", ticker: "ALO.PA", mnemo: "ALO", secteur: "Transport & Logistique", siege: "France" },
  { nom: "Alten", ticker: "ATE.PA", mnemo: "ATE", secteur: "Services & Technologie", siege: "France" },
  { nom: "Amundi", ticker: "AMUN.PA", mnemo: "AMUN", secteur: "Banque & Finance", siege: "France" },
  { nom: "Aperam", ticker: "APAM.PA", mnemo: "APAM", secteur: "Industrie & Matériaux", siege: "Luxembourg" },
  { nom: "ArcelorMittal", ticker: "MT.PA", mnemo: "MT", secteur: "Industrie & Matériaux", siege: "Luxembourg" },
  { nom: "Argan", ticker: "ARG.PA", mnemo: "ARG", secteur: "Immobilier", siege: "France" },
  { nom: "Arkema", ticker: "AKE.PA", mnemo: "AKE", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Atos", ticker: "ATO.PA", mnemo: "ATO", secteur: "Services & Technologie", siege: "France" },
  { nom: "Axa", ticker: "CS.PA", mnemo: "CS", secteur: "Assurance", siege: "France" },
  { nom: "Ayvens", ticker: "AYV.PA", mnemo: "AYV", secteur: "Automobile", siege: "France" },
  { nom: "Bénéteau", ticker: "BEN.PA", mnemo: "BEN", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Bic", ticker: "BB.PA", mnemo: "BB", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "bioMérieux", ticker: "BIM.PA", mnemo: "BIM", secteur: "Santé", siege: "France" },
  { nom: "BNP Paribas", ticker: "BNP.PA", mnemo: "BNP", secteur: "Banque & Finance", siege: "France" },
  { nom: "Bolloré", ticker: "BOL.PA", mnemo: "BOL", secteur: "Transport & Logistique", siege: "France" },
  { nom: "Bouygues", ticker: "EN.PA", mnemo: "EN", secteur: "BTP & Concessions", siege: "France" },
  { nom: "Bureau Veritas", ticker: "BVI.PA", mnemo: "BVI", secteur: "Services & Technologie", siege: "France" },
  { nom: "Capgemini", ticker: "CAP.PA", mnemo: "CAP", secteur: "Services & Technologie", siege: "France" },
  { nom: "Carmila", ticker: "CARM.PA", mnemo: "CARM", secteur: "Immobilier", siege: "France" },
  { nom: "Carrefour", ticker: "CA.PA", mnemo: "CA", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "Clariane", ticker: "CLARI.PA", mnemo: "CLARI", secteur: "Santé", siege: "France" },
  { nom: "Coface", ticker: "COFA.PA", mnemo: "COFA", secteur: "Assurance", siege: "France" },
  { nom: "Covivio", ticker: "COV.PA", mnemo: "COV", secteur: "Immobilier", siege: "France" },
  { nom: "Crédit Agricole", ticker: "ACA.PA", mnemo: "ACA", secteur: "Banque & Finance", siege: "France" },
  { nom: "Danone", ticker: "BN.PA", mnemo: "BN", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "Dassault Aviation", ticker: "AM.PA", mnemo: "AM", secteur: "Aéronautique & Défense", siege: "France" },
  { nom: "Dassault Systèmes", ticker: "DSY.PA", mnemo: "DSY", secteur: "Services & Technologie", siege: "France" },
  { nom: "Derichebourg", ticker: "DBG.PA", mnemo: "DBG", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Edenred", ticker: "EDEN.PA", mnemo: "EDEN", secteur: "Services & Technologie", siege: "France" },
  { nom: "Eiffage", ticker: "FGR.PA", mnemo: "FGR", secteur: "BTP & Concessions", siege: "France" },
  { nom: "Elior", ticker: "ELIOR.PA", mnemo: "ELIOR", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "Elis", ticker: "ELIS.PA", mnemo: "ELIS", secteur: "Services & Technologie", siege: "France" },
  { nom: "Emeis", ticker: "EMEIS.PA", mnemo: "EMEIS", secteur: "Santé", siege: "France" },
  { nom: "Engie", ticker: "ENGI.PA", mnemo: "ENGI", secteur: "Énergie & Utilities", siege: "France" },
  { nom: "Eramet", ticker: "ERA.PA", mnemo: "ERA", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "EssilorLuxottica", ticker: "EL.PA", mnemo: "EL", secteur: "Luxe & Cosmétiques", siege: "France" },
  { nom: "Esso", ticker: "ES.PA", mnemo: "ES", secteur: "Énergie & Utilities", siege: "France" },
  { nom: "Eurazeo", ticker: "RF.PA", mnemo: "RF", secteur: "Banque & Finance", siege: "France" },
  { nom: "Eurofins Scientific", ticker: "ERF.PA", mnemo: "ERF", secteur: "Santé", siege: "Luxembourg" },
  { nom: "Euronext", ticker: "ENX.PA", mnemo: "ENX", secteur: "Banque & Finance", siege: "Pays-Bas" },
  { nom: "FDJ United", ticker: "FDJU.PA", mnemo: "FDJU", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "Forvia", ticker: "FRVIA.PA", mnemo: "FRVIA", secteur: "Automobile", siege: "France" },
  { nom: "Gecina", ticker: "GFC.PA", mnemo: "GFC", secteur: "Immobilier", siege: "France" },
  { nom: "Getlink", ticker: "GET.PA", mnemo: "GET", secteur: "Transport & Logistique", siege: "France" },
  { nom: "GTT (Gaztransport & Technigaz)", ticker: "GTT.PA", mnemo: "GTT", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Hermès International", ticker: "RMS.PA", mnemo: "RMS", secteur: "Luxe & Cosmétiques", siege: "France" },
  { nom: "Icade", ticker: "ICAD.PA", mnemo: "ICAD", secteur: "Immobilier", siege: "France" },
  { nom: "ID Logistics", ticker: "IDL.PA", mnemo: "IDL", secteur: "Transport & Logistique", siege: "France" },
  { nom: "Imerys", ticker: "NK.PA", mnemo: "NK", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Interparfums", ticker: "ITP.PA", mnemo: "ITP", secteur: "Luxe & Cosmétiques", siege: "France" },
  { nom: "Ipsen", ticker: "IPN.PA", mnemo: "IPN", secteur: "Santé", siege: "France" },
  { nom: "Ipsos", ticker: "IPS.PA", mnemo: "IPS", secteur: "Services & Technologie", siege: "France" },
  { nom: "JCDecaux", ticker: "DEC.PA", mnemo: "DEC", secteur: "Médias & Communication", siege: "France" },
  { nom: "Kering", ticker: "KER.PA", mnemo: "KER", secteur: "Luxe & Cosmétiques", siege: "France" },
  { nom: "Klepierre", ticker: "LI.PA", mnemo: "LI", secteur: "Immobilier", siege: "France" },
  { nom: "L'Oréal", ticker: "OR.PA", mnemo: "OR", secteur: "Luxe & Cosmétiques", siege: "France" },
  { nom: "Legrand", ticker: "LR.PA", mnemo: "LR", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "LVMH", ticker: "MC.PA", mnemo: "MC", secteur: "Luxe & Cosmétiques", siege: "France" },
  { nom: "Maurel & Prom", ticker: "MAU.PA", mnemo: "MAU", secteur: "Énergie & Utilities", siege: "France" },
  { nom: "MedinCell", ticker: "MEDCL.PA", mnemo: "MEDCL", secteur: "Santé", siege: "France" },
  { nom: "Mercialys", ticker: "MERY.PA", mnemo: "MERY", secteur: "Immobilier", siege: "France" },
  { nom: "Mersen", ticker: "MRN.PA", mnemo: "MRN", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "M6 Métropole Télévision", ticker: "MMT.PA", mnemo: "MMT", secteur: "Médias & Communication", siege: "France" },
  { nom: "Michelin", ticker: "ML.PA", mnemo: "ML", secteur: "Automobile", siege: "France" },
  { nom: "Neoen", ticker: "NEOEN.PA", mnemo: "NEOEN", secteur: "Énergie & Utilities", siege: "France" },
  { nom: "Nexans", ticker: "NEX.PA", mnemo: "NEX", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Nexity", ticker: "NXI.PA", mnemo: "NXI", secteur: "Immobilier", siege: "France" },
  { nom: "OPmobility", ticker: "OPM.PA", mnemo: "OPM", secteur: "Automobile", siege: "France" },
  { nom: "Orange", ticker: "ORA.PA", mnemo: "ORA", secteur: "Services & Technologie", siege: "France" },
  { nom: "Pernod Ricard", ticker: "RI.PA", mnemo: "RI", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "Planisware", ticker: "PLNW.PA", mnemo: "PLNW", secteur: "Services & Technologie", siege: "France" },
  { nom: "Pluxee", ticker: "PLX.PA", mnemo: "PLX", secteur: "Services & Technologie", siege: "France" },
  { nom: "Publicis Groupe", ticker: "PUB.PA", mnemo: "PUB", secteur: "Médias & Communication", siege: "France" },
  { nom: "Rémy Cointreau", ticker: "RCO.PA", mnemo: "RCO", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "Renault", ticker: "RNO.PA", mnemo: "RNO", secteur: "Automobile", siege: "France" },
  { nom: "Rexel", ticker: "RXL.PA", mnemo: "RXL", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Robertet", ticker: "RBT.PA", mnemo: "RBT", secteur: "Luxe & Cosmétiques", siege: "France" },
  { nom: "Rubis", ticker: "RUI.PA", mnemo: "RUI", secteur: "Énergie & Utilities", siege: "France" },
  { nom: "SEB", ticker: "SK.PA", mnemo: "SK", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Safran", ticker: "SAF.PA", mnemo: "SAF", secteur: "Aéronautique & Défense", siege: "France" },
  { nom: "Saint-Gobain", ticker: "SGO.PA", mnemo: "SGO", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Sanofi", ticker: "SAN.PA", mnemo: "SAN", secteur: "Santé", siege: "France" },
  { nom: "Sartorius Stedim Biotech", ticker: "DIM.PA", mnemo: "DIM", secteur: "Santé", siege: "France" },
  { nom: "Schneider Electric", ticker: "SU.PA", mnemo: "SU", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Scor", ticker: "SCR.PA", mnemo: "SCR", secteur: "Assurance", siege: "France" },
  { nom: "SES", ticker: "SESG.PA", mnemo: "SESG", secteur: "Services & Technologie", siege: "Luxembourg" },
  { nom: "Société Générale", ticker: "GLE.PA", mnemo: "GLE", secteur: "Banque & Finance", siege: "France" },
  { nom: "Sodexo", ticker: "SW.PA", mnemo: "SW", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "Soitec", ticker: "SOI.PA", mnemo: "SOI", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Solvay", ticker: "SOLB.PA", mnemo: "SOLB", secteur: "Industrie & Matériaux", siege: "Belgique" },
  { nom: "Sopra Steria", ticker: "SOP.PA", mnemo: "SOP", secteur: "Services & Technologie", siege: "France" },
  { nom: "Spie", ticker: "SPIE.PA", mnemo: "SPIE", secteur: "BTP & Concessions", siege: "France" },
  { nom: "Stellantis", ticker: "STLAP.PA", mnemo: "STLA", secteur: "Automobile", siege: "Pays-Bas" },
  { nom: "STMicroelectronics", ticker: "STM.PA", mnemo: "STM", secteur: "Services & Technologie", siege: "Pays-Bas" },
  { nom: "Technip Energies", ticker: "TE.PA", mnemo: "TE", secteur: "Énergie & Utilities", siege: "France" },
  { nom: "Teleperformance", ticker: "TEP.PA", mnemo: "TEP", secteur: "Services & Technologie", siege: "France" },
  { nom: "TF1", ticker: "TFI.PA", mnemo: "TFI", secteur: "Médias & Communication", siege: "France" },
  { nom: "Thales", ticker: "HO.PA", mnemo: "HO", secteur: "Aéronautique & Défense", siege: "France" },
  { nom: "TotalEnergies", ticker: "TTE.PA", mnemo: "TTE", secteur: "Énergie & Utilities", siege: "France" },
  { nom: "Trigano", ticker: "TRI.PA", mnemo: "TRI", secteur: "Consommation & Distribution", siege: "France" },
  { nom: "Ubisoft Entertainment", ticker: "UBI.PA", mnemo: "UBI", secteur: "Services & Technologie", siege: "France" },
  { nom: "Unibail-Rodamco-Westfield", ticker: "URW.PA", mnemo: "URW", secteur: "Immobilier", siege: "France" },
  { nom: "Valeo", ticker: "FR.PA", mnemo: "FR", secteur: "Automobile", siege: "France" },
  { nom: "Vallourec", ticker: "VK.PA", mnemo: "VK", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Valneva", ticker: "VLA.PA", mnemo: "VLA", secteur: "Santé", siege: "France" },
  { nom: "Veolia Environnement", ticker: "VIE.PA", mnemo: "VIE", secteur: "Énergie & Utilities", siege: "France" },
  { nom: "Verallia", ticker: "VRLA.PA", mnemo: "VRLA", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Vicat", ticker: "VCT.PA", mnemo: "VCT", secteur: "Industrie & Matériaux", siege: "France" },
  { nom: "Vinci", ticker: "DG.PA", mnemo: "DG", secteur: "BTP & Concessions", siege: "France" },
  { nom: "Virbac", ticker: "VIRP.PA", mnemo: "VIRP", secteur: "Santé", siege: "France" },
  { nom: "Viridien", ticker: "VIRI.PA", mnemo: "VIRI", secteur: "Services & Technologie", siege: "France" },
  { nom: "VusionGroup", ticker: "VU.PA", mnemo: "VU", secteur: "Services & Technologie", siege: "France" },
  { nom: "Wendel", ticker: "MF.PA", mnemo: "MF", secteur: "Banque & Finance", siege: "France" },
  { nom: "Worldline", ticker: "WLN.PA", mnemo: "WLN", secteur: "Services & Technologie", siege: "France" },
];

// Univers S&P 500 : les grandes capitalisations américaines, composition
// relevée sur Wikipedia (à jour à quelques semaines près des changements
// de composition trimestriels de S&P Dow Jones Indices). Tickers Yahoo
// Finance : les classes d'actions (ex. BRK.B) utilisent un tiret plutôt
// qu'un point (BRK-B), convention Yahoo Finance pour les tickers américains.
export const SP500: Valeur[] = [
  { nom: "3M", ticker: "MMM", mnemo: "MMM", secteur: "Industrie", siege: "États-Unis" },
  { nom: "A. O. Smith", ticker: "AOS", mnemo: "AOS", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Abbott Laboratories", ticker: "ABT", mnemo: "ABT", secteur: "Santé", siege: "États-Unis" },
  { nom: "AbbVie", ticker: "ABBV", mnemo: "ABBV", secteur: "Santé", siege: "États-Unis" },
  { nom: "Accenture", ticker: "ACN", mnemo: "ACN", secteur: "Technologie", siege: "Irlande" },
  { nom: "Adobe Inc.", ticker: "ADBE", mnemo: "ADBE", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Advanced Micro Devices", ticker: "AMD", mnemo: "AMD", secteur: "Technologie", siege: "États-Unis" },
  { nom: "AES Corporation", ticker: "AES", mnemo: "AES", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Aflac", ticker: "AFL", mnemo: "AFL", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Agilent Technologies", ticker: "A", mnemo: "A", secteur: "Santé", siege: "États-Unis" },
  { nom: "Air Products", ticker: "APD", mnemo: "APD", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Airbnb", ticker: "ABNB", mnemo: "ABNB", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Akamai Technologies", ticker: "AKAM", mnemo: "AKAM", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Albemarle Corporation", ticker: "ALB", mnemo: "ALB", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Alexandria Real Estate Equities", ticker: "ARE", mnemo: "ARE", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Align Technology", ticker: "ALGN", mnemo: "ALGN", secteur: "Santé", siege: "États-Unis" },
  { nom: "Allegion", ticker: "ALLE", mnemo: "ALLE", secteur: "Industrie", siege: "Irlande" },
  { nom: "Alliant Energy", ticker: "LNT", mnemo: "LNT", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Allstate", ticker: "ALL", mnemo: "ALL", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Alphabet Inc. (Class A)", ticker: "GOOGL", mnemo: "GOOGL", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Alphabet Inc. (Class C)", ticker: "GOOG", mnemo: "GOOG", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Altria", ticker: "MO", mnemo: "MO", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Amazon", ticker: "AMZN", mnemo: "AMZN", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Amcor", ticker: "AMCR", mnemo: "AMCR", secteur: "Matériaux", siege: "Royaume-Uni" },
  { nom: "Ameren", ticker: "AEE", mnemo: "AEE", secteur: "Services publics", siege: "États-Unis" },
  { nom: "American Electric Power", ticker: "AEP", mnemo: "AEP", secteur: "Services publics", siege: "États-Unis" },
  { nom: "American Express", ticker: "AXP", mnemo: "AXP", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "American International Group", ticker: "AIG", mnemo: "AIG", secteur: "Assurance", siege: "États-Unis" },
  { nom: "American Tower", ticker: "AMT", mnemo: "AMT", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "American Water Works", ticker: "AWK", mnemo: "AWK", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Ameriprise Financial", ticker: "AMP", mnemo: "AMP", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Ametek", ticker: "AME", mnemo: "AME", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Amgen", ticker: "AMGN", mnemo: "AMGN", secteur: "Santé", siege: "États-Unis" },
  { nom: "Amphenol", ticker: "APH", mnemo: "APH", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Analog Devices", ticker: "ADI", mnemo: "ADI", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Aon plc", ticker: "AON", mnemo: "AON", secteur: "Assurance", siege: "Royaume-Uni" },
  { nom: "APA Corporation", ticker: "APA", mnemo: "APA", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Apollo Global Management", ticker: "APO", mnemo: "APO", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Apple Inc.", ticker: "AAPL", mnemo: "AAPL", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Applied Materials", ticker: "AMAT", mnemo: "AMAT", secteur: "Technologie", siege: "États-Unis" },
  { nom: "AppLovin", ticker: "APP", mnemo: "APP", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Aptiv", ticker: "APTV", mnemo: "APTV", secteur: "Consommation discrétionnaire", siege: "Suisse" },
  { nom: "Arch Capital Group", ticker: "ACGL", mnemo: "ACGL", secteur: "Assurance", siege: "Bermudes" },
  { nom: "Archer Daniels Midland", ticker: "ADM", mnemo: "ADM", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Ares Management", ticker: "ARES", mnemo: "ARES", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Arista Networks", ticker: "ANET", mnemo: "ANET", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Arthur J. Gallagher & Co.", ticker: "AJG", mnemo: "AJG", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Assurant", ticker: "AIZ", mnemo: "AIZ", secteur: "Assurance", siege: "États-Unis" },
  { nom: "AT&T", ticker: "T", mnemo: "T", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Atmos Energy", ticker: "ATO", mnemo: "ATO", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Autodesk", ticker: "ADSK", mnemo: "ADSK", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Automatic Data Processing", ticker: "ADP", mnemo: "ADP", secteur: "Industrie", siege: "États-Unis" },
  { nom: "AutoZone", ticker: "AZO", mnemo: "AZO", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "AvalonBay Communities", ticker: "AVB", mnemo: "AVB", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Avery Dennison", ticker: "AVY", mnemo: "AVY", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Axon Enterprise", ticker: "AXON", mnemo: "AXON", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Baker Hughes", ticker: "BKR", mnemo: "BKR", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Ball Corporation", ticker: "BALL", mnemo: "BALL", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Bank of America", ticker: "BAC", mnemo: "BAC", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Baxter International", ticker: "BAX", mnemo: "BAX", secteur: "Santé", siege: "États-Unis" },
  { nom: "Becton Dickinson", ticker: "BDX", mnemo: "BDX", secteur: "Santé", siege: "États-Unis" },
  { nom: "Berkshire Hathaway", ticker: "BRK-B", mnemo: "BRK-B", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Best Buy", ticker: "BBY", mnemo: "BBY", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Bio-Techne", ticker: "TECH", mnemo: "TECH", secteur: "Santé", siege: "États-Unis" },
  { nom: "Biogen", ticker: "BIIB", mnemo: "BIIB", secteur: "Santé", siege: "États-Unis" },
  { nom: "BlackRock", ticker: "BLK", mnemo: "BLK", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Blackstone Inc.", ticker: "BX", mnemo: "BX", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Block, Inc.", ticker: "XYZ", mnemo: "XYZ", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "BNY Mellon", ticker: "BNY", mnemo: "BNY", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Boeing", ticker: "BA", mnemo: "BA", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Booking Holdings", ticker: "BKNG", mnemo: "BKNG", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Boston Scientific", ticker: "BSX", mnemo: "BSX", secteur: "Santé", siege: "États-Unis" },
  { nom: "Bristol Myers Squibb", ticker: "BMY", mnemo: "BMY", secteur: "Santé", siege: "États-Unis" },
  { nom: "Broadcom", ticker: "AVGO", mnemo: "AVGO", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Broadridge Financial Solutions", ticker: "BR", mnemo: "BR", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Brown & Brown", ticker: "BRO", mnemo: "BRO", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Brown–Forman", ticker: "BF-B", mnemo: "BF-B", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Builders FirstSource", ticker: "BLDR", mnemo: "BLDR", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Bunge Global", ticker: "BG", mnemo: "BG", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "BXP, Inc.", ticker: "BXP", mnemo: "BXP", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "C.H. Robinson", ticker: "CHRW", mnemo: "CHRW", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Cadence Design Systems", ticker: "CDNS", mnemo: "CDNS", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Camden Property Trust", ticker: "CPT", mnemo: "CPT", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Campbell's Company (The)", ticker: "CPB", mnemo: "CPB", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Capital One", ticker: "COF", mnemo: "COF", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Cardinal Health", ticker: "CAH", mnemo: "CAH", secteur: "Santé", siege: "États-Unis" },
  { nom: "Carnival Corporation", ticker: "CCL", mnemo: "CCL", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Carrier Global", ticker: "CARR", mnemo: "CARR", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Carvana", ticker: "CVNA", mnemo: "CVNA", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Casey's", ticker: "CASY", mnemo: "CASY", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Caterpillar Inc.", ticker: "CAT", mnemo: "CAT", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Cboe Global Markets", ticker: "CBOE", mnemo: "CBOE", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "CBRE Group", ticker: "CBRE", mnemo: "CBRE", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "CDW Corporation", ticker: "CDW", mnemo: "CDW", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Cencora", ticker: "COR", mnemo: "COR", secteur: "Santé", siege: "États-Unis" },
  { nom: "Centene Corporation", ticker: "CNC", mnemo: "CNC", secteur: "Santé", siege: "États-Unis" },
  { nom: "CenterPoint Energy", ticker: "CNP", mnemo: "CNP", secteur: "Services publics", siege: "États-Unis" },
  { nom: "CF Industries", ticker: "CF", mnemo: "CF", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Charles River Laboratories", ticker: "CRL", mnemo: "CRL", secteur: "Santé", siege: "États-Unis" },
  { nom: "Charles Schwab Corporation", ticker: "SCHW", mnemo: "SCHW", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Charter Communications", ticker: "CHTR", mnemo: "CHTR", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Chevron Corporation", ticker: "CVX", mnemo: "CVX", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Chipotle Mexican Grill", ticker: "CMG", mnemo: "CMG", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Chubb Limited", ticker: "CB", mnemo: "CB", secteur: "Assurance", siege: "Suisse" },
  { nom: "Church & Dwight", ticker: "CHD", mnemo: "CHD", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Ciena", ticker: "CIEN", mnemo: "CIEN", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Cigna", ticker: "CI", mnemo: "CI", secteur: "Santé", siege: "États-Unis" },
  { nom: "Cincinnati Financial", ticker: "CINF", mnemo: "CINF", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Cintas", ticker: "CTAS", mnemo: "CTAS", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Cisco", ticker: "CSCO", mnemo: "CSCO", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Citigroup", ticker: "C", mnemo: "C", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Citizens Financial Group", ticker: "CFG", mnemo: "CFG", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Clorox", ticker: "CLX", mnemo: "CLX", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "CME Group", ticker: "CME", mnemo: "CME", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "CMS Energy", ticker: "CMS", mnemo: "CMS", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Coca-Cola Company (The)", ticker: "KO", mnemo: "KO", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Cognizant", ticker: "CTSH", mnemo: "CTSH", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Coherent Corp.", ticker: "COHR", mnemo: "COHR", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Coinbase", ticker: "COIN", mnemo: "COIN", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Colgate-Palmolive", ticker: "CL", mnemo: "CL", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Comcast", ticker: "CMCSA", mnemo: "CMCSA", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Comfort Systems USA", ticker: "FIX", mnemo: "FIX", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Conagra Brands", ticker: "CAG", mnemo: "CAG", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "ConocoPhillips", ticker: "COP", mnemo: "COP", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Consolidated Edison", ticker: "ED", mnemo: "ED", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Constellation Brands", ticker: "STZ", mnemo: "STZ", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Constellation Energy", ticker: "CEG", mnemo: "CEG", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Cooper Companies (The)", ticker: "COO", mnemo: "COO", secteur: "Santé", siege: "États-Unis" },
  { nom: "Copart", ticker: "CPRT", mnemo: "CPRT", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Corning Inc.", ticker: "GLW", mnemo: "GLW", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Corpay", ticker: "CPAY", mnemo: "CPAY", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Corteva", ticker: "CTVA", mnemo: "CTVA", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "CoStar Group", ticker: "CSGP", mnemo: "CSGP", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Costco", ticker: "COST", mnemo: "COST", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "CRH plc", ticker: "CRH", mnemo: "CRH", secteur: "Matériaux", siege: "Irlande" },
  { nom: "CrowdStrike", ticker: "CRWD", mnemo: "CRWD", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Crown Castle", ticker: "CCI", mnemo: "CCI", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "CSX Corporation", ticker: "CSX", mnemo: "CSX", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Cummins", ticker: "CMI", mnemo: "CMI", secteur: "Industrie", siege: "États-Unis" },
  { nom: "CVS Health", ticker: "CVS", mnemo: "CVS", secteur: "Santé", siege: "États-Unis" },
  { nom: "Danaher Corporation", ticker: "DHR", mnemo: "DHR", secteur: "Santé", siege: "États-Unis" },
  { nom: "Darden Restaurants", ticker: "DRI", mnemo: "DRI", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Datadog", ticker: "DDOG", mnemo: "DDOG", secteur: "Technologie", siege: "États-Unis" },
  { nom: "DaVita", ticker: "DVA", mnemo: "DVA", secteur: "Santé", siege: "États-Unis" },
  { nom: "Deckers Brands", ticker: "DECK", mnemo: "DECK", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Deere & Company", ticker: "DE", mnemo: "DE", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Dell Technologies", ticker: "DELL", mnemo: "DELL", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Delta Air Lines", ticker: "DAL", mnemo: "DAL", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Devon Energy", ticker: "DVN", mnemo: "DVN", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Dexcom", ticker: "DXCM", mnemo: "DXCM", secteur: "Santé", siege: "États-Unis" },
  { nom: "Diamondback Energy", ticker: "FANG", mnemo: "FANG", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Digital Realty", ticker: "DLR", mnemo: "DLR", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Dollar General", ticker: "DG", mnemo: "DG", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Dollar Tree", ticker: "DLTR", mnemo: "DLTR", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Dominion Energy", ticker: "D", mnemo: "D", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Domino's", ticker: "DPZ", mnemo: "DPZ", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "DoorDash", ticker: "DASH", mnemo: "DASH", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Dover Corporation", ticker: "DOV", mnemo: "DOV", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Dow Inc.", ticker: "DOW", mnemo: "DOW", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "D. R. Horton", ticker: "DHI", mnemo: "DHI", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "DTE Energy", ticker: "DTE", mnemo: "DTE", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Duke Energy", ticker: "DUK", mnemo: "DUK", secteur: "Services publics", siege: "États-Unis" },
  { nom: "DuPont", ticker: "DD", mnemo: "DD", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Eaton Corporation", ticker: "ETN", mnemo: "ETN", secteur: "Industrie", siege: "Irlande" },
  { nom: "eBay Inc.", ticker: "EBAY", mnemo: "EBAY", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "EchoStar", ticker: "SATS", mnemo: "SATS", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Ecolab", ticker: "ECL", mnemo: "ECL", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Edison International", ticker: "EIX", mnemo: "EIX", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Edwards Lifesciences", ticker: "EW", mnemo: "EW", secteur: "Santé", siege: "États-Unis" },
  { nom: "Electronic Arts", ticker: "EA", mnemo: "EA", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Elevance Health", ticker: "ELV", mnemo: "ELV", secteur: "Santé", siege: "États-Unis" },
  { nom: "Emcor", ticker: "EME", mnemo: "EME", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Emerson Electric", ticker: "EMR", mnemo: "EMR", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Entergy", ticker: "ETR", mnemo: "ETR", secteur: "Services publics", siege: "États-Unis" },
  { nom: "EOG Resources", ticker: "EOG", mnemo: "EOG", secteur: "Énergie", siege: "États-Unis" },
  { nom: "EPAM Systems", ticker: "EPAM", mnemo: "EPAM", secteur: "Technologie", siege: "États-Unis" },
  { nom: "EQT Corporation", ticker: "EQT", mnemo: "EQT", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Equifax", ticker: "EFX", mnemo: "EFX", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Equinix", ticker: "EQIX", mnemo: "EQIX", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Equity Residential", ticker: "EQR", mnemo: "EQR", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Erie Indemnity", ticker: "ERIE", mnemo: "ERIE", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Essex Property Trust", ticker: "ESS", mnemo: "ESS", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Estée Lauder Companies (The)", ticker: "EL", mnemo: "EL", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Everest Group", ticker: "EG", mnemo: "EG", secteur: "Assurance", siege: "Bermudes" },
  { nom: "Evergy", ticker: "EVRG", mnemo: "EVRG", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Eversource Energy", ticker: "ES", mnemo: "ES", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Exelon", ticker: "EXC", mnemo: "EXC", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Expand Energy", ticker: "EXE", mnemo: "EXE", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Expedia Group", ticker: "EXPE", mnemo: "EXPE", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Expeditors International", ticker: "EXPD", mnemo: "EXPD", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Extra Space Storage", ticker: "EXR", mnemo: "EXR", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "ExxonMobil", ticker: "XOM", mnemo: "XOM", secteur: "Énergie", siege: "États-Unis" },
  { nom: "F5, Inc.", ticker: "FFIV", mnemo: "FFIV", secteur: "Technologie", siege: "États-Unis" },
  { nom: "FactSet", ticker: "FDS", mnemo: "FDS", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Fair Isaac", ticker: "FICO", mnemo: "FICO", secteur: "Technologie", siege: "Montana" },
  { nom: "Fastenal", ticker: "FAST", mnemo: "FAST", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Federal Realty Investment Trust", ticker: "FRT", mnemo: "FRT", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "FedEx", ticker: "FDX", mnemo: "FDX", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Fidelity National Information Services", ticker: "FIS", mnemo: "FIS", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Fifth Third Bancorp", ticker: "FITB", mnemo: "FITB", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "First Solar", ticker: "FSLR", mnemo: "FSLR", secteur: "Technologie", siege: "États-Unis" },
  { nom: "FirstEnergy", ticker: "FE", mnemo: "FE", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Fiserv", ticker: "FISV", mnemo: "FISV", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Ford Motor Company", ticker: "F", mnemo: "F", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Fortinet", ticker: "FTNT", mnemo: "FTNT", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Fortive", ticker: "FTV", mnemo: "FTV", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Fox Corporation (Class A)", ticker: "FOXA", mnemo: "FOXA", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Fox Corporation (Class B)", ticker: "FOX", mnemo: "FOX", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Franklin Resources", ticker: "BEN", mnemo: "BEN", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Freeport-McMoRan", ticker: "FCX", mnemo: "FCX", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Garmin", ticker: "GRMN", mnemo: "GRMN", secteur: "Consommation discrétionnaire", siege: "Suisse" },
  { nom: "Gartner", ticker: "IT", mnemo: "IT", secteur: "Technologie", siege: "États-Unis" },
  { nom: "GE Aerospace", ticker: "GE", mnemo: "GE", secteur: "Industrie", siege: "États-Unis" },
  { nom: "GE HealthCare", ticker: "GEHC", mnemo: "GEHC", secteur: "Santé", siege: "États-Unis" },
  { nom: "GE Vernova", ticker: "GEV", mnemo: "GEV", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Gen Digital", ticker: "GEN", mnemo: "GEN", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Generac", ticker: "GNRC", mnemo: "GNRC", secteur: "Industrie", siege: "États-Unis" },
  { nom: "General Dynamics", ticker: "GD", mnemo: "GD", secteur: "Industrie", siege: "États-Unis" },
  { nom: "General Mills", ticker: "GIS", mnemo: "GIS", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "General Motors", ticker: "GM", mnemo: "GM", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Genuine Parts Company", ticker: "GPC", mnemo: "GPC", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Gilead Sciences", ticker: "GILD", mnemo: "GILD", secteur: "Santé", siege: "États-Unis" },
  { nom: "Global Payments", ticker: "GPN", mnemo: "GPN", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Globe Life", ticker: "GL", mnemo: "GL", secteur: "Assurance", siege: "États-Unis" },
  { nom: "GoDaddy", ticker: "GDDY", mnemo: "GDDY", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Goldman Sachs", ticker: "GS", mnemo: "GS", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Halliburton", ticker: "HAL", mnemo: "HAL", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Hartford (The)", ticker: "HIG", mnemo: "HIG", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Hasbro", ticker: "HAS", mnemo: "HAS", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "HCA Healthcare", ticker: "HCA", mnemo: "HCA", secteur: "Santé", siege: "États-Unis" },
  { nom: "Healthpeak Properties", ticker: "DOC", mnemo: "DOC", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Henry Schein", ticker: "HSIC", mnemo: "HSIC", secteur: "Santé", siege: "États-Unis" },
  { nom: "Hershey Company (The)", ticker: "HSY", mnemo: "HSY", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Hewlett Packard Enterprise", ticker: "HPE", mnemo: "HPE", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Hilton Worldwide", ticker: "HLT", mnemo: "HLT", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Home Depot (The)", ticker: "HD", mnemo: "HD", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Honeywell", ticker: "HON", mnemo: "HON", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Hormel Foods", ticker: "HRL", mnemo: "HRL", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Host Hotels & Resorts", ticker: "HST", mnemo: "HST", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Howmet Aerospace", ticker: "HWM", mnemo: "HWM", secteur: "Industrie", siege: "États-Unis" },
  { nom: "HP Inc.", ticker: "HPQ", mnemo: "HPQ", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Hubbell Incorporated", ticker: "HUBB", mnemo: "HUBB", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Humana", ticker: "HUM", mnemo: "HUM", secteur: "Santé", siege: "États-Unis" },
  { nom: "Huntington Bancshares", ticker: "HBAN", mnemo: "HBAN", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Huntington Ingalls Industries", ticker: "HII", mnemo: "HII", secteur: "Industrie", siege: "États-Unis" },
  { nom: "IBM", ticker: "IBM", mnemo: "IBM", secteur: "Technologie", siege: "États-Unis" },
  { nom: "IDEX Corporation", ticker: "IEX", mnemo: "IEX", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Idexx Laboratories", ticker: "IDXX", mnemo: "IDXX", secteur: "Santé", siege: "Maine" },
  { nom: "Illinois Tool Works", ticker: "ITW", mnemo: "ITW", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Incyte", ticker: "INCY", mnemo: "INCY", secteur: "Santé", siege: "États-Unis" },
  { nom: "Ingersoll Rand", ticker: "IR", mnemo: "IR", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Insulet Corporation", ticker: "PODD", mnemo: "PODD", secteur: "Santé", siege: "États-Unis" },
  { nom: "Intel", ticker: "INTC", mnemo: "INTC", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Interactive Brokers", ticker: "IBKR", mnemo: "IBKR", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Intercontinental Exchange", ticker: "ICE", mnemo: "ICE", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "International Flavors & Fragrances", ticker: "IFF", mnemo: "IFF", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "International Paper", ticker: "IP", mnemo: "IP", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Intuit", ticker: "INTU", mnemo: "INTU", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Intuitive Surgical", ticker: "ISRG", mnemo: "ISRG", secteur: "Santé", siege: "États-Unis" },
  { nom: "Invesco", ticker: "IVZ", mnemo: "IVZ", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Invitation Homes", ticker: "INVH", mnemo: "INVH", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "IQVIA", ticker: "IQV", mnemo: "IQV", secteur: "Santé", siege: "États-Unis" },
  { nom: "Iron Mountain", ticker: "IRM", mnemo: "IRM", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "J.B. Hunt", ticker: "JBHT", mnemo: "JBHT", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Jabil", ticker: "JBL", mnemo: "JBL", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Jack Henry & Associates", ticker: "JKHY", mnemo: "JKHY", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Jacobs Solutions", ticker: "J", mnemo: "J", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Johnson & Johnson", ticker: "JNJ", mnemo: "JNJ", secteur: "Santé", siege: "États-Unis" },
  { nom: "Johnson Controls", ticker: "JCI", mnemo: "JCI", secteur: "Industrie", siege: "Irlande" },
  { nom: "JPMorgan Chase", ticker: "JPM", mnemo: "JPM", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Kenvue", ticker: "KVUE", mnemo: "KVUE", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Keurig Dr Pepper", ticker: "KDP", mnemo: "KDP", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "KeyCorp", ticker: "KEY", mnemo: "KEY", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Keysight Technologies", ticker: "KEYS", mnemo: "KEYS", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Kimberly-Clark", ticker: "KMB", mnemo: "KMB", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Kimco Realty", ticker: "KIM", mnemo: "KIM", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Kinder Morgan", ticker: "KMI", mnemo: "KMI", secteur: "Énergie", siege: "États-Unis" },
  { nom: "KKR & Co.", ticker: "KKR", mnemo: "KKR", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "KLA Corporation", ticker: "KLAC", mnemo: "KLAC", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Kraft Heinz", ticker: "KHC", mnemo: "KHC", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Kroger", ticker: "KR", mnemo: "KR", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "L3Harris", ticker: "LHX", mnemo: "LHX", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Labcorp", ticker: "LH", mnemo: "LH", secteur: "Santé", siege: "États-Unis" },
  { nom: "Lam Research", ticker: "LRCX", mnemo: "LRCX", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Las Vegas Sands", ticker: "LVS", mnemo: "LVS", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Leidos", ticker: "LDOS", mnemo: "LDOS", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Lennar", ticker: "LEN", mnemo: "LEN", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Lennox International", ticker: "LII", mnemo: "LII", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Lilly (Eli)", ticker: "LLY", mnemo: "LLY", secteur: "Santé", siege: "États-Unis" },
  { nom: "Linde plc", ticker: "LIN", mnemo: "LIN", secteur: "Matériaux", siege: "Royaume-Uni" },
  { nom: "Live Nation Entertainment", ticker: "LYV", mnemo: "LYV", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Lockheed Martin", ticker: "LMT", mnemo: "LMT", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Loews Corporation", ticker: "L", mnemo: "L", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Lowe's", ticker: "LOW", mnemo: "LOW", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Lululemon Athletica", ticker: "LULU", mnemo: "LULU", secteur: "Consommation discrétionnaire", siege: "Canada" },
  { nom: "Lumentum", ticker: "LITE", mnemo: "LITE", secteur: "Technologie", siege: "États-Unis" },
  { nom: "LyondellBasell", ticker: "LYB", mnemo: "LYB", secteur: "Matériaux", siege: "Pays-Bas" },
  { nom: "M&T Bank", ticker: "MTB", mnemo: "MTB", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Marathon Petroleum", ticker: "MPC", mnemo: "MPC", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Marriott International", ticker: "MAR", mnemo: "MAR", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Marsh McLennan", ticker: "MRSH", mnemo: "MRSH", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Martin Marietta Materials", ticker: "MLM", mnemo: "MLM", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Masco", ticker: "MAS", mnemo: "MAS", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Mastercard", ticker: "MA", mnemo: "MA", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "McCormick & Company", ticker: "MKC", mnemo: "MKC", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "McDonald's", ticker: "MCD", mnemo: "MCD", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "McKesson Corporation", ticker: "MCK", mnemo: "MCK", secteur: "Santé", siege: "États-Unis" },
  { nom: "Medtronic", ticker: "MDT", mnemo: "MDT", secteur: "Santé", siege: "Irlande" },
  { nom: "Merck & Co.", ticker: "MRK", mnemo: "MRK", secteur: "Santé", siege: "États-Unis" },
  { nom: "Meta Platforms", ticker: "META", mnemo: "META", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "MetLife", ticker: "MET", mnemo: "MET", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Mettler Toledo", ticker: "MTD", mnemo: "MTD", secteur: "Santé", siege: "États-Unis" },
  { nom: "MGM Resorts", ticker: "MGM", mnemo: "MGM", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Microchip Technology", ticker: "MCHP", mnemo: "MCHP", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Micron Technology", ticker: "MU", mnemo: "MU", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Microsoft", ticker: "MSFT", mnemo: "MSFT", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Mid-America Apartment Communities", ticker: "MAA", mnemo: "MAA", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Moderna", ticker: "MRNA", mnemo: "MRNA", secteur: "Santé", siege: "États-Unis" },
  { nom: "Molson Coors Beverage Company", ticker: "TAP", mnemo: "TAP", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Mondelez International", ticker: "MDLZ", mnemo: "MDLZ", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Monolithic Power Systems", ticker: "MPWR", mnemo: "MPWR", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Monster Beverage", ticker: "MNST", mnemo: "MNST", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Moody's Corporation", ticker: "MCO", mnemo: "MCO", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Morgan Stanley", ticker: "MS", mnemo: "MS", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Mosaic Company (The)", ticker: "MOS", mnemo: "MOS", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Motorola Solutions", ticker: "MSI", mnemo: "MSI", secteur: "Technologie", siege: "États-Unis" },
  { nom: "MSCI Inc.", ticker: "MSCI", mnemo: "MSCI", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Nasdaq, Inc.", ticker: "NDAQ", mnemo: "NDAQ", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "NetApp", ticker: "NTAP", mnemo: "NTAP", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Netflix", ticker: "NFLX", mnemo: "NFLX", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Newmont", ticker: "NEM", mnemo: "NEM", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "News Corp (Class A)", ticker: "NWSA", mnemo: "NWSA", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "News Corp (Class B)", ticker: "NWS", mnemo: "NWS", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "NextEra Energy", ticker: "NEE", mnemo: "NEE", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Nike, Inc.", ticker: "NKE", mnemo: "NKE", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "NiSource", ticker: "NI", mnemo: "NI", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Nordson Corporation", ticker: "NDSN", mnemo: "NDSN", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Norfolk Southern", ticker: "NSC", mnemo: "NSC", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Northern Trust", ticker: "NTRS", mnemo: "NTRS", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Northrop Grumman", ticker: "NOC", mnemo: "NOC", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Norwegian Cruise Line Holdings", ticker: "NCLH", mnemo: "NCLH", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "NRG Energy", ticker: "NRG", mnemo: "NRG", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Nucor", ticker: "NUE", mnemo: "NUE", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Nvidia", ticker: "NVDA", mnemo: "NVDA", secteur: "Technologie", siege: "États-Unis" },
  { nom: "NVR, Inc.", ticker: "NVR", mnemo: "NVR", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "NXP Semiconductors", ticker: "NXPI", mnemo: "NXPI", secteur: "Technologie", siege: "Pays-Bas" },
  { nom: "O'Reilly Automotive", ticker: "ORLY", mnemo: "ORLY", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Occidental Petroleum", ticker: "OXY", mnemo: "OXY", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Old Dominion", ticker: "ODFL", mnemo: "ODFL", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Omnicom Group", ticker: "OMC", mnemo: "OMC", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "ON Semiconductor", ticker: "ON", mnemo: "ON", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Oneok", ticker: "OKE", mnemo: "OKE", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Oracle Corporation", ticker: "ORCL", mnemo: "ORCL", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Otis Worldwide", ticker: "OTIS", mnemo: "OTIS", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Paccar", ticker: "PCAR", mnemo: "PCAR", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Packaging Corporation of America", ticker: "PKG", mnemo: "PKG", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Palantir Technologies", ticker: "PLTR", mnemo: "PLTR", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Palo Alto Networks", ticker: "PANW", mnemo: "PANW", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Paramount Skydance Corporation", ticker: "PSKY", mnemo: "PSKY", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Parker Hannifin", ticker: "PH", mnemo: "PH", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Paychex", ticker: "PAYX", mnemo: "PAYX", secteur: "Industrie", siege: "États-Unis" },
  { nom: "PayPal", ticker: "PYPL", mnemo: "PYPL", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Pentair", ticker: "PNR", mnemo: "PNR", secteur: "Industrie", siege: "Royaume-Uni" },
  { nom: "PepsiCo", ticker: "PEP", mnemo: "PEP", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Pfizer", ticker: "PFE", mnemo: "PFE", secteur: "Santé", siege: "États-Unis" },
  { nom: "PG&E Corporation", ticker: "PCG", mnemo: "PCG", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Philip Morris International", ticker: "PM", mnemo: "PM", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Phillips 66", ticker: "PSX", mnemo: "PSX", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Pinnacle West Capital", ticker: "PNW", mnemo: "PNW", secteur: "Services publics", siege: "États-Unis" },
  { nom: "PNC Financial Services", ticker: "PNC", mnemo: "PNC", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Pool Corporation", ticker: "POOL", mnemo: "POOL", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "PPG Industries", ticker: "PPG", mnemo: "PPG", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "PPL Corporation", ticker: "PPL", mnemo: "PPL", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Principal Financial Group", ticker: "PFG", mnemo: "PFG", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Procter & Gamble", ticker: "PG", mnemo: "PG", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Progressive Corporation", ticker: "PGR", mnemo: "PGR", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Prologis", ticker: "PLD", mnemo: "PLD", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Prudential Financial", ticker: "PRU", mnemo: "PRU", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Public Service Enterprise Group", ticker: "PEG", mnemo: "PEG", secteur: "Services publics", siege: "États-Unis" },
  { nom: "PTC Inc.", ticker: "PTC", mnemo: "PTC", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Public Storage", ticker: "PSA", mnemo: "PSA", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "PulteGroup", ticker: "PHM", mnemo: "PHM", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Quanta Services", ticker: "PWR", mnemo: "PWR", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Qualcomm", ticker: "QCOM", mnemo: "QCOM", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Quest Diagnostics", ticker: "DGX", mnemo: "DGX", secteur: "Santé", siege: "États-Unis" },
  { nom: "Qnity Electronics", ticker: "Q", mnemo: "Q", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Ralph Lauren Corporation", ticker: "RL", mnemo: "RL", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Raymond James Financial", ticker: "RJF", mnemo: "RJF", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "RTX Corporation", ticker: "RTX", mnemo: "RTX", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Realty Income", ticker: "O", mnemo: "O", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Regency Centers", ticker: "REG", mnemo: "REG", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Regeneron Pharmaceuticals", ticker: "REGN", mnemo: "REGN", secteur: "Santé", siege: "États-Unis" },
  { nom: "Regions Financial Corporation", ticker: "RF", mnemo: "RF", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Republic Services", ticker: "RSG", mnemo: "RSG", secteur: "Industrie", siege: "États-Unis" },
  { nom: "ResMed", ticker: "RMD", mnemo: "RMD", secteur: "Santé", siege: "États-Unis" },
  { nom: "Revvity", ticker: "RVTY", mnemo: "RVTY", secteur: "Santé", siege: "États-Unis" },
  { nom: "Robinhood Markets", ticker: "HOOD", mnemo: "HOOD", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Rockwell Automation", ticker: "ROK", mnemo: "ROK", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Rollins, Inc.", ticker: "ROL", mnemo: "ROL", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Roper Technologies", ticker: "ROP", mnemo: "ROP", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Ross Stores", ticker: "ROST", mnemo: "ROST", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Royal Caribbean Group", ticker: "RCL", mnemo: "RCL", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "S&P Global", ticker: "SPGI", mnemo: "SPGI", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Salesforce", ticker: "CRM", mnemo: "CRM", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Sandisk", ticker: "SNDK", mnemo: "SNDK", secteur: "Technologie", siege: "États-Unis" },
  { nom: "SBA Communications", ticker: "SBAC", mnemo: "SBAC", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Schlumberger", ticker: "SLB", mnemo: "SLB", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Seagate Technology", ticker: "STX", mnemo: "STX", secteur: "Technologie", siege: "Irlande" },
  { nom: "Sempra", ticker: "SRE", mnemo: "SRE", secteur: "Services publics", siege: "États-Unis" },
  { nom: "ServiceNow", ticker: "NOW", mnemo: "NOW", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Sherwin-Williams", ticker: "SHW", mnemo: "SHW", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Simon Property Group", ticker: "SPG", mnemo: "SPG", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Skyworks Solutions", ticker: "SWKS", mnemo: "SWKS", secteur: "Technologie", siege: "États-Unis" },
  { nom: "J.M. Smucker Company (The)", ticker: "SJM", mnemo: "SJM", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Smurfit Westrock", ticker: "SW", mnemo: "SW", secteur: "Matériaux", siege: "Irlande" },
  { nom: "Snap-on", ticker: "SNA", mnemo: "SNA", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Solventum", ticker: "SOLV", mnemo: "SOLV", secteur: "Santé", siege: "États-Unis" },
  { nom: "Southern Company", ticker: "SO", mnemo: "SO", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Southwest Airlines", ticker: "LUV", mnemo: "LUV", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Stanley Black & Decker", ticker: "SWK", mnemo: "SWK", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Starbucks", ticker: "SBUX", mnemo: "SBUX", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "State Street Corporation", ticker: "STT", mnemo: "STT", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Steel Dynamics", ticker: "STLD", mnemo: "STLD", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "Steris", ticker: "STE", mnemo: "STE", secteur: "Santé", siege: "Irlande" },
  { nom: "Stryker Corporation", ticker: "SYK", mnemo: "SYK", secteur: "Santé", siege: "États-Unis" },
  { nom: "Supermicro", ticker: "SMCI", mnemo: "SMCI", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Synchrony Financial", ticker: "SYF", mnemo: "SYF", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Synopsys", ticker: "SNPS", mnemo: "SNPS", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Sysco", ticker: "SYY", mnemo: "SYY", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "T-Mobile US", ticker: "TMUS", mnemo: "TMUS", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "T. Rowe Price", ticker: "TROW", mnemo: "TROW", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Take-Two Interactive", ticker: "TTWO", mnemo: "TTWO", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Tapestry, Inc.", ticker: "TPR", mnemo: "TPR", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Targa Resources", ticker: "TRGP", mnemo: "TRGP", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Target Corporation", ticker: "TGT", mnemo: "TGT", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "TE Connectivity", ticker: "TEL", mnemo: "TEL", secteur: "Technologie", siege: "Irlande" },
  { nom: "Teledyne Technologies", ticker: "TDY", mnemo: "TDY", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Teradyne", ticker: "TER", mnemo: "TER", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Tesla, Inc.", ticker: "TSLA", mnemo: "TSLA", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Texas Instruments", ticker: "TXN", mnemo: "TXN", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Texas Pacific Land Corporation", ticker: "TPL", mnemo: "TPL", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Textron", ticker: "TXT", mnemo: "TXT", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Thermo Fisher Scientific", ticker: "TMO", mnemo: "TMO", secteur: "Santé", siege: "États-Unis" },
  { nom: "TJX Companies", ticker: "TJX", mnemo: "TJX", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "TKO Group Holdings", ticker: "TKO", mnemo: "TKO", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Trade Desk (The)", ticker: "TTD", mnemo: "TTD", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Tractor Supply", ticker: "TSCO", mnemo: "TSCO", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Trane Technologies", ticker: "TT", mnemo: "TT", secteur: "Industrie", siege: "Irlande" },
  { nom: "TransDigm Group", ticker: "TDG", mnemo: "TDG", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Travelers Companies (The)", ticker: "TRV", mnemo: "TRV", secteur: "Assurance", siege: "États-Unis" },
  { nom: "Trimble Inc.", ticker: "TRMB", mnemo: "TRMB", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Truist Financial", ticker: "TFC", mnemo: "TFC", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Tyler Technologies", ticker: "TYL", mnemo: "TYL", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Tyson Foods", ticker: "TSN", mnemo: "TSN", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "U.S. Bancorp", ticker: "USB", mnemo: "USB", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Uber", ticker: "UBER", mnemo: "UBER", secteur: "Industrie", siege: "États-Unis" },
  { nom: "UDR, Inc.", ticker: "UDR", mnemo: "UDR", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Ulta Beauty", ticker: "ULTA", mnemo: "ULTA", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Union Pacific Corporation", ticker: "UNP", mnemo: "UNP", secteur: "Industrie", siege: "États-Unis" },
  { nom: "United Airlines Holdings", ticker: "UAL", mnemo: "UAL", secteur: "Industrie", siege: "États-Unis" },
  { nom: "United Parcel Service", ticker: "UPS", mnemo: "UPS", secteur: "Industrie", siege: "États-Unis" },
  { nom: "United Rentals", ticker: "URI", mnemo: "URI", secteur: "Industrie", siege: "États-Unis" },
  { nom: "UnitedHealth Group", ticker: "UNH", mnemo: "UNH", secteur: "Santé", siege: "États-Unis" },
  { nom: "Universal Health Services", ticker: "UHS", mnemo: "UHS", secteur: "Santé", siege: "États-Unis" },
  { nom: "Valero Energy", ticker: "VLO", mnemo: "VLO", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Veeva Systems", ticker: "VEEV", mnemo: "VEEV", secteur: "Santé", siege: "États-Unis" },
  { nom: "Ventas", ticker: "VTR", mnemo: "VTR", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Veralto", ticker: "VLTO", mnemo: "VLTO", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Verisign", ticker: "VRSN", mnemo: "VRSN", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Verisk Analytics", ticker: "VRSK", mnemo: "VRSK", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Verizon", ticker: "VZ", mnemo: "VZ", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Vertex Pharmaceuticals", ticker: "VRTX", mnemo: "VRTX", secteur: "Santé", siege: "États-Unis" },
  { nom: "Vertiv", ticker: "VRT", mnemo: "VRT", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Viatris", ticker: "VTRS", mnemo: "VTRS", secteur: "Santé", siege: "États-Unis" },
  { nom: "Vici Properties", ticker: "VICI", mnemo: "VICI", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Visa Inc.", ticker: "V", mnemo: "V", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Vistra Corp.", ticker: "VST", mnemo: "VST", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Vulcan Materials Company", ticker: "VMC", mnemo: "VMC", secteur: "Matériaux", siege: "États-Unis" },
  { nom: "W. R. Berkley Corporation", ticker: "WRB", mnemo: "WRB", secteur: "Assurance", siege: "États-Unis" },
  { nom: "W. W. Grainger", ticker: "GWW", mnemo: "GWW", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Wabtec", ticker: "WAB", mnemo: "WAB", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Walmart", ticker: "WMT", mnemo: "WMT", secteur: "Consommation de base", siege: "États-Unis" },
  { nom: "Walt Disney Company (The)", ticker: "DIS", mnemo: "DIS", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Warner Bros. Discovery", ticker: "WBD", mnemo: "WBD", secteur: "Communication & Médias", siege: "États-Unis" },
  { nom: "Waste Management", ticker: "WM", mnemo: "WM", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Waters Corporation", ticker: "WAT", mnemo: "WAT", secteur: "Santé", siege: "États-Unis" },
  { nom: "WEC Energy Group", ticker: "WEC", mnemo: "WEC", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Wells Fargo", ticker: "WFC", mnemo: "WFC", secteur: "Banque & Finance", siege: "États-Unis" },
  { nom: "Welltower", ticker: "WELL", mnemo: "WELL", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "West Pharmaceutical Services", ticker: "WST", mnemo: "WST", secteur: "Santé", siege: "États-Unis" },
  { nom: "Western Digital", ticker: "WDC", mnemo: "WDC", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Weyerhaeuser", ticker: "WY", mnemo: "WY", secteur: "Immobilier", siege: "États-Unis" },
  { nom: "Williams-Sonoma, Inc.", ticker: "WSM", mnemo: "WSM", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Williams Companies", ticker: "WMB", mnemo: "WMB", secteur: "Énergie", siege: "États-Unis" },
  { nom: "Willis Towers Watson", ticker: "WTW", mnemo: "WTW", secteur: "Assurance", siege: "Royaume-Uni" },
  { nom: "Workday, Inc.", ticker: "WDAY", mnemo: "WDAY", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Wynn Resorts", ticker: "WYNN", mnemo: "WYNN", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Xcel Energy", ticker: "XEL", mnemo: "XEL", secteur: "Services publics", siege: "États-Unis" },
  { nom: "Xylem Inc.", ticker: "XYL", mnemo: "XYL", secteur: "Industrie", siege: "États-Unis" },
  { nom: "Yum! Brands", ticker: "YUM", mnemo: "YUM", secteur: "Consommation discrétionnaire", siege: "États-Unis" },
  { nom: "Zebra Technologies", ticker: "ZBRA", mnemo: "ZBRA", secteur: "Technologie", siege: "États-Unis" },
  { nom: "Zimmer Biomet", ticker: "ZBH", mnemo: "ZBH", secteur: "Santé", siege: "États-Unis" },
  { nom: "Zoetis", ticker: "ZTS", mnemo: "ZTS", secteur: "Santé", siege: "États-Unis" },
];

export interface DefinitionUnivers {
  code: CodeUnivers;
  nom: string;
  indiceTicker: string;
  indiceNom: string;
  valeurs: Valeur[];
}

export const UNIVERSS: Record<CodeUnivers, DefinitionUnivers> = {
  sbf120: {
    code: "sbf120",
    nom: "SBF 120",
    indiceTicker: "^FCHI",
    indiceNom: "CAC 40",
    valeurs: SBF120,
  },
  sp500: {
    code: "sp500",
    nom: "S&P 500",
    indiceTicker: "^GSPC",
    indiceNom: "S&P 500",
    valeurs: SP500,
  },
};

export const UNIVERS_PAR_DEFAUT: CodeUnivers = "sbf120";

// Combine les deux univers — utilisé par le comparateur, qui permet de
// chercher une valeur indépendamment de l'univers actuellement affiché
// sur le tableau principal (on peut ainsi comparer une valeur française à
// une valeur américaine).
export const TOUTES_VALEURS: Valeur[] = [...SBF120, ...SP500];

export function secteursPour(code: CodeUnivers): Secteur[] {
  return Array.from(new Set(UNIVERSS[code].valeurs.map((v) => v.secteur))).sort();
}

// Recherche une valeur par ticker à travers tous les univers connus (les
// symboles ne se chevauchent pas : suffixe .PA pour Euronext Paris, aucun
// suffixe pour les tickers américains).
export function trouverValeur(ticker: string): Valeur | undefined {
  return SBF120.find((v) => v.ticker === ticker) ?? SP500.find((v) => v.ticker === ticker);
}
